export const db = "queue-underflow"
export const questionCollection = "questions"
export const answerCollection = "answers"
export const complaintCollection = "complaints"
export const commentCollection = "comments"
export const voteCollection = "votes"
export const questionAttachmentBucket = "question-attachments"